apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp
  labels:
    app: healthapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthapp
  template:
    metadata:
      labels:
        app: healthapp
    spec:
      containers:
      - name: healthapp
        image: abhipatil1390/javaproject:latest
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: healthapp
spec:
  selector:
    app: healthapp
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
